// package main

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"

	"github.com/go-audio/audio"
	"github.com/joho/godotenv"
	witai "github.com/wit-ai/wit-go"
)

type errorResp struct {
	Body  string `json:"body"`
	Error string `json:"error"`
}

type MessageResponse struct {
	ID       string                 `json:"msg_id"`
	Text     string                 `json:"_text"`
	Entities map[string]interface{} `json:"entities"`
}


func main() {
	err := godotenv.Load(".env")

	witAiToken := os.Getenv("WIT_AI_TOKEN")


	// init witAi client
	witAiClient := witai.NewClient(witAiToken)
	fmt.Println(witAiClient.Version) // so go doesn't throw error

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	// curl -XPOST 'https://api.wit.ai/speech' -i -H "Authorization: Bearer DFMDUQWIE74UNGG2SDJ5N5E7EWLDLMKQ" -H "Content-Type: audio/ogg" --data-binary "@hohoho.ogg"

	// f, err := os.Open("hohoho.ogg")
	// if err != nil {
	// 	// handle err
	// }
	// defer f.Close()
	// req, err := http.NewRequest("POST", "https://api.wit.ai/speech", f)
	// if err != nil {
	// 	// handle err
	// }
	// req.Header.Set("Authorization", "Bearer DFMDUQWIE74UNGG2SDJ5N5E7EWLDLMKQ")
	// req.Header.Set("Content-Type", "audio/ogg")

	// resp, err := http.DefaultClient.Do(req)
	// if err != nil {
	// 	// handle err
	// 	fmt.Println(err)
	// }
	// defer resp.Body.Close()
	// var msgResp *MessageResponse
	// decoder := json.NewDecoder(resp.Body)
	// err = decoder.Decode(&msgResp)
	// fmt.Println(msgResp, msgResp.Text)



	file, err := os.ReadFile("hohoho.ogg")
	if err != nil {
		fmt.Println("can't open file:" ,err)
	}
	
	// // bypass witgo library since not working properly
	body := bytes.NewBuffer(file)
	req, err := http.NewRequest("POST", "https://api.wit.ai/speech", body)
	if err != nil {
		fmt.Println(err)
	}
	
	headerAuth := fmt.Sprintf("Bearer %s", witAiToken)
	headerAccept := fmt.Sprintf("application/vnd.wit.%s+json", "20170307")
	contentType := "audio/ogg"
	
	req.Header.Set("Authorization", headerAuth)
	req.Header.Set("Accept", headerAccept)
	req.Header.Set("Content-Type", contentType)

	httpClient := &http.Client{
		Timeout: time.Second * 10,
	}
	resp, err := httpClient.Do(req)
	if err != nil {
		fmt.Println(err)
	}

	if resp.StatusCode >= http.StatusBadRequest {
		defer resp.Body.Close()

		var e *errorResp
		decoder := json.NewDecoder(resp.Body)
		err = decoder.Decode(&e)
		if err != nil {
			fmt.Println(fmt.Errorf("unable to decode error message: %s", err.Error()))
		}

		// Wit.ai errors sometimes have "error", sometimes "body" message
		if len(e.Error) > 0 {
			fmt.Println(fmt.Errorf("unable to make a request. error: %s", e.Error))
		}

		if len(e.Body) > 0 {
			fmt.Println(fmt.Errorf("unable to make a request. error: %s", e.Body))
		}
	}

	var msgResp *MessageResponse
	decoder := json.NewDecoder(resp.Body)
	err = decoder.Decode(&msgResp)

	//fmt.Println("owo is: ", gencurl.FromRequest(req))
	fmt.Println(msgResp, msgResp.Text, err)


	//send to wit AI to parse	
	// file, err := os.Open("570650.ogg")
	
	// speech := witai.Speech{File: file, ContentType: "audio/ogg",}
	// msg_request := witai.MessageRequest{ Speech: &speech,}
	// msg, err := witAiClient.Speech(&msg_request)
	// file.Close()
	// if err != nil {
	// 	fmt.Println("can't send to witAi:", err)
	// }
	// fmt.Println(msg, msg.Text)
}

func newAudioIntBuffer(r io.Reader) (*audio.IntBuffer, error) {
	buf := audio.IntBuffer{
		Format: &audio.Format{
			NumChannels: 1,
			SampleRate:  8000,
		},
	}
	for {
		var sample int16
		err := binary.Read(r, binary.LittleEndian, &sample)
		switch {
		case err == io.EOF:
			return &buf, nil
		case err != nil:
			return nil, err
		}
		buf.Data = append(buf.Data, int(sample))
	}
}